import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Main from '../components/main'
import Abours from '../components/Abours'

import Sec from '../components/Sec'
import ContactUs from '../pages/contact'
import Footer from '../components/Footer'




export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <div>
        
          <Main/>
          
          <About/>
          <Sec/>
          <ContactUs/>
          <Footer/>

        
        


          
          
          
      
      </div>

      


      
    </div>
  )
}
